# Generated by Django 5.1 on 2024-11-15 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
