# Generated by Django 5.1 on 2024-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_events_start_date_add_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
