# Generated by Django 5.1 on 2024-11-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.CharField(blank=True, default='https://cdn2.iconfinder.com/data/icons/instagram-ui/48/jee-75-512.png', max_length=255, null=True),
        ),
    ]
