# Generated by Django 5.1 on 2024-11-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_alter_user_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('publishedAt', models.TextField(max_length=1000, null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('url', models.TextField(max_length=1000, null=True)),
                ('urlToImage', models.TextField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
