# Generated by Django 5.1 on 2024-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
